# Generated by Django 4.1 on 2022-09-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
    ]
