# Generated by Django 4.1 on 2022-09-14 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_bid_new_bid_alter_listing_base_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="base_bid",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(99999999.99),
                ]
            ),
        ),
    ]
