# Generated by Django 4.1 on 2022-09-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_category_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name="listing", name="img", field=models.URLField(blank=True),
        ),
    ]
