# Generated by Django 4.1 on 2022-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_comment_comment_alter_listing_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=32),
        ),
    ]
