# Generated by Django 4.1 on 2022-09-28 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_bid_item_remove_listing_base_bid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="bid", name="new_bid", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="curr_bid",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(99999999.99),
                ]
            ),
        ),
    ]
