# Generated by Django 4.1 on 2022-10-02 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_listing_curr_bid"),
    ]

    operations = [
        migrations.RemoveField(model_name="bid", name="item",),
        migrations.RemoveField(model_name="listing", name="curr_bid",),
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bid",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="new_bid",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(99999999.99),
                ]
            ),
        ),
    ]
