# Generated by Django 4.1 on 2022-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
