# Generated by Django 4.1 on 2022-09-13 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_bid_user_alter_comment_user_alter_listing_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid", name="new_bid", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="base_bid",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
