# Generated by Django 4.1 on 2022-10-03 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("[deleted]"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
