# Generated by Django 4.1 on 2022-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="username",
            field=models.CharField(default="[deleted]", max_length=128),
        ),
    ]
